### ISSUE TITLE
Only getting few informations of my HS2-10K-T2-X-WiFi

### ISSUE THREAD

**Issue by Bloodemi** [djansen1987/SAJeSolar#100]
Hello there,
im new in Home Assistant and wanted to get my eSAJ or "Elekeeper" now Informations read out by Home Assistant.
i saw this nice integration but i can only get few informations of my Inverter/Battery...
Here is a screenshot of the informations i get:
![grafik](https://github.com/user-attachments/assets/534d293b-d7e6-43c3-ba41-5e77c1cf1244)
![grafik](https://github.com/user-attachments/assets/611ca2ee-7fb4-4934-bed2-490d4f4cb735)

i already did also a Debug command saw in #86 but i dunno if you have for the debug the right informations from me... i guess the roborock integration has also an issue that i would try to fix by another github page... :D

```
2024-11-21 04:12:44.550 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: nowPower State: 0.0
2024-11-21 04:12:44.550 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: runningState State: Yes
2024-11-21 04:12:44.550 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: todayElectricity State: 0.0
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: monthElectricity State: 101.21
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: yearElectricity State: 6871.13
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalElectricity State: 6871.13
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: todayGridIncome State: None
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: income State: None
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: lastUploadTime State: 2024-11-21 04:05:57
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalPlantTreeNum State: 12.18
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalReduceCo2 State: 6.85
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: plantuid State: C9911622383A4B33BE01BD7BDA896F4A
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: currency State: €
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: address State: xxx
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: isOnline State: Y
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: status State: success
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: peakPower State: None
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: pvElec State: None
2024-11-21 04:12:44.551 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: useElec State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: buyElec State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: sellElec State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: buyRate State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: sellRate State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedRate1 State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedRate2 State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedEnergy1 State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedEnergy2 State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: plantTreeNum State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: reduceCo2 State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalGridPower State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalLoadPower State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalPvgenPower State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: gridLoadPower State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: solarLoadPower State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: homeLoadPower State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: exportPower State: None
2024-11-21 04:12:44.552 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalPvEnergy State: None
2024-11-21 04:12:44.553 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalLoadEnergy State: None
2024-11-21 04:12:44.553 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalBuyEnergy State: None
2024-11-21 04:12:44.553 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalSellEnergy State: None
2024-11-21 04:12:44.889 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 145, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roborock/select.py", line 152, in current_option
    return self.coordinator.maps[current_map].name
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 62
2024-11-21 04:12:45.054 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 145, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roborock/select.py", line 152, in current_option
    return self.coordinator.maps[current_map].name
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 62
```

If you could help me out this would be lovely! ❤️

**Comment by Bloodemi** [comment]
nevermind, Issue is solved. I used the https://github.com/stanus74/home-assistant-saj-h2-modbus Integration and it worked perfectly for me!
