### ISSUE TITLE
Issues reading battery data.

### ISSUE THREAD

**Issue by reneneumann** [djansen1987/SAJeSolar#87]
Hi, 

I'm using this plugin for a while without major issues but since day 1 do I have an issue getting my battery data gathered by home assistant. The log displayes the following lines:

```
2024-08-25 19:50:46.809 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: isOnline State: Y
2024-08-25 19:50:46.809 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: status State: success
2024-08-25 19:50:46.809 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: systemPower State: 5.0
2024-08-25 19:50:46.809 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: sellElec State: None
2024-08-25 19:50:46.809 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: buyRate State: None
2024-08-25 19:50:46.810 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: sellRate State: None
2024-08-25 19:50:46.810 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedRate1 State: None
2024-08-25 19:50:46.810 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedRate2 State: None
2024-08-25 19:50:46.829 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedEnergy1 State: None
2024-08-25 19:50:46.830 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfConsumedEnergy2 State: None
2024-08-25 19:50:46.830 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: chargeElec State: None
2024-08-25 19:50:46.830 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: dischargeElec State: None
2024-08-25 19:51:16.805 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: nowPower State: 271.0
2024-08-25 19:51:16.806 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: runningState State: Yes
2024-08-25 19:51:16.806 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: devOnlineNum State: Yes
2024-08-25 19:51:16.806 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: todayElectricity State: 11.33
2024-08-25 19:51:16.807 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: monthElectricity State: 536.97
2024-08-25 19:51:16.807 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: yearElectricity State: 3162.03
2024-08-25 19:51:16.807 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalElectricity State: 3162.86
2024-08-25 19:51:16.807 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: selfUseRate State: 73.99%
2024-08-25 19:51:16.807 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalBuyElec State: 805.64
2024-08-25 19:51:16.808 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalConsumpElec State: 3157.4
2024-08-25 19:51:16.808 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalSellElec State: 822.81
2024-08-25 19:51:16.808 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: lastUploadTime State: 2024-08-25 19:44:30
2024-08-25 19:51:16.808 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalPlantTreeNum State: 5.61
2024-08-25 19:51:16.808 DEBUG (MainThread) [custom_components.saj_esolar.sensor] Device: totalReduceCo2 State: 3.15
```

I tried for the repo the manual test python script and this reported the values for:
chargeElec
dischargeElec

Below is an example:

```
{
  "pageNo": 1,
  "pageSize": 10,
  "plantList": [
    {
      "plantuid": "CFA...F44",
      "plantname": "",
      "systempower": 5.0,
      "type": 1,
      "installername": "",
      "countryCode": "",
      "country": "Ireland",
      "province": "",
      "city": "",
      "county": "",
      "foreignRemark": "",
      "address": ".....SAJ B2 5kWh",
      "latitude": 0.0,
      "longitude": 0.0,
      "createDateStr": "2024-08-24 13:37:16",
      "isOnline": "Y",
      "runningState": 1,
      "nowPower": 498.0,
      "todayElectricity": 10.21,
      "totalElectricity": 2708.7,
      "enableEdit": "Y",
      "enableDelete": "Y",
      "enableVisitor": "Y",
      "isFavorite": "0",
      "isRename": 0,
      "isMulBind": 0,
      "isTimeError": 0,
      "plantDetail": {
        "type": 1,
        "runningState": 1,
        "nowPower": 498.0,
        "todayElectricity": 10.21,
        "monthElectricity": 82.81,
        "yearElectricity": 2707.87,
        "totalElectricity": 2708.7,
        "totalConsumpElec": 2633.88,
        "totalBuyElec": 667.01,
        "totalSellElec": 750.63,
        "selfUseRate": "72.29%",
        "devOnlineNum": 1,
        "devTotalNum": 1,
        "totalPlantTreeNum": 4.8,
        "totalReduceCo2": 2.7,
        "lastUploadTime": "2024-08-24 18:09:32",
        "userType": 2,
        "snList": [
          "H1X...592"
        ],
        "energyCompareYearList": [
          "2024"
        ]
      },
      "status": "success",
      "beanList": [
        {
          "pvElec": 10.21,
          "useElec": 23.41,
          "buyElec": 10.33,
          "sellElec": 0.31,
          "chargeElec": 0.7,
          "dischargeElec": 3.88,
          "buyRate": "44.13%",
          "sellRate": "3.04%",
          "selfConsumedRate1": "96.96%",
          "selfConsumedRate2": "55.87%",
          "selfConsumedEnergy1": 9.9,
          "selfConsumedEnergy2": 13.08,
          "plantTreeNum": 0.018,
          "reduceCo2": 0.01,
          "dataTime": 1722700800000,
          "devicesn": "H1X...592"
        }
      ],
      "kitList": [
        {
          "invType": "",
          "kitType": "N/A",
          "monthSellEnergyStr": "82.81",
          "todaySellEnergy": 0.0,
          "kitSn": "N/A",
          "updateDateStr": "2024-08-24 01:09:32",
          "ifShowAFCI": 0,
          "powernower": "499",
          "mastermcufw": "v1.362",
          "type": 1,
          "devicetype": "H1-5K-S2-15",
          "onLineStr": "1",
          "displayfw": "v3.019",
          "devicepc": "1020082400EN055200",
          "powernow": 499.0,
          "isShowBattery": 1,
          "owner": "N/A",
          "todaySellEnergyStr": "N/A",
          "index": 0,
          "monthSellEnergy": 82.81,
          "devicesn": "H1X....592",
          "userId": "814....001",
          "onLine": 0,
          "slavemcufw": "v1.362",
          "isModuleExpire": 0,
          "totalSellEnergy": 2708.7,
          "totalSellEnergyStr": "2,708.7",
          "isShowHighVoltBat": 1,
          "isHistory": 0,
          "mark": 1,
          "plantName": "N/A",
          "dataTimeStr": "2024-08-24 18:05:00",
          "findRawdataPageList": {
            "nowPrower": 498.0,
            "rOutPowerWattStr": "1",
            "todayBackupLoadEnergy": 0.03,
            "totalBackupLoadEnergy": 4.25,
            "batPower": -1.0,
            "rBackupPowerWatt": 1.0,
            "pV3StrCurr1Str": "N/A",
            "timeStart": "null 00:00:00",
            "pV4Curr": 0.0,
            "currSelfConsumePowerStr": "9",
            "rOutVolt": 240.2,
            "totalPVEnergy": 2708.7,
            "tOutVolt": 0.0,
            "createTimeStr": "2024-08-24 01:09:41",
            "deviceType": 1,
            "pV4StrCurr2Str": "N/A",
            "pv3SeriesCurrent": "0.0-0.0-0.0-0.0",
            "rGridFreqStr": "49.96",
            "totalBatDisEnergy": 684.1,
            "tOutFreqStr": "0",
            "isExport": false,
            "sGridPowerWattStr": "0",
            "totalBatChgEnergy": 675.3,
            "isAdmin": "N",
            "pV1StrCurr4": 0.0,
            "pV1StrCurr3": 0.0,
            "pV1StrCurr2": 0.0,
            "pV1StrCurr1": 0.0,
            "pv2SeriesCurrent": "0.0-0.0-0.0-0.0",
            "POP": 494.0,
            "RST": 1,
            "pvInputMode": "0",
            "rGridFreq": 49.96,
            "sGridFreqStr": "0",
            "sGridVoltStr": "0",
            "tOutPowerVAStr": "0",
            "pV4VoltStr": "0",
            "batEnergyPercent": 22.0,
            "backupTotalLoadPowerWatt": 1.0,
            "tableStoreTimeEnd": "",
            "tOutVoltStr": "0",
            "rGridVoltStr": "240.4",
            "batVoltStr": "51.9",
            "tGridCurrStr": "0.0",
            "rGridCurr": 3.85,
            "rOutFreqStr": "49.95",
            "userId": "",
            "partitionName": "",
            "sGridVolt": 0.0,
            "pV3PowerStr": "0",
            "tOnGridOutVolt": 0.0,
            "tGridPowerWattStr": "0",
            "pV2StrCurr4Str": "N/A",
            "ctPVPowerWattStr": "0",
            "pV4StrCurr3Str": "N/A",
            "tOutPowerWatt": 0.0,
            "pV3Power": 0.0,
            "pV1CurrStr": "0.91",
            "pV2CurrStr": "0.76",
            "pV4CurrStr": "0.0",
            "onLineStr": "Y",
            "pV2Power": 193.0,
            "todayBatDisEnergy": 3.88,
            "pac": 0.0,
            "officeId": "",
            "rOutPowerWatt": 1.0,
            "pacStr": "0",
            "powernow": 0.0,
            "ctPvCurr": 0.0,
            "tGridVoltStr": "0",
            "powerNower": "N/A",
            "pvChannelList": [],
            "pv1SeriesCurrent": "0.0-0.0-0.0-0.0",
            "pV1Power": 306.0,
            "pV4Volt": 0.0,
            "pV3StrCurr2Str": "N/A",
            "deviceTempStr": "0",
            "rOutCurr": 0.0,
            "tOutCurr": 0.0,
            "todayFeedInEnergyStr": "10.33",
            "totalPVEnergyStr": "2,708.7",
            "pV3Curr": 0.0,
            "sOnGridOutPowerWatt": 0.0,
            "tGridFreqStr": "0",
            "todayBatChgEnergy": 0.7,
            "pV1StrCurr1Str": "N/A",
            "tGridFreq": 0.0,
            "totalFeedInEnergy": 667.01,
            "sOutPowerVAStr": "0",
            "gridDirection": 0,
            "batCurrStr": "-0.02",
            "powerNow": 0.0,
            "rOutPowerVA": 9.0,
            "kitType": "N/A",
            "pV1VoltStr": "335.8",
            "todayLoadEnergy": 0.0,
            "sOutPowerWattStr": "0",
            "pV4StrCurr1": 0.0,
            "sGridPowerVA": 0.0,
            "pV4StrCurr2": 0.0,
            "pV4StrCurr3": 0.0,
            "pV4StrCurr4": 0.0,
            "sOutPowerVA": 0.0,
            "batType": "2",
            "pV3Volt": 0.1,
            "rGridPowerVAStr": "769",
            "tGridPowerVAStr": "0",
            "tGridCurr": 0.0,
            "rOnGridOutFreq": 49.96,
            "pV4StrCurr4Str": "N/A",
            "tOutFreq": 0.0,
            "todayPVEnergy": 10.21,
            "tGridPowerWatt": 0.0,
            "sGridPowerVAStr": "0",
            "tOutCurrStr": "0.0",
            "ctPvCurrStr": "0",
            "pV2Curr": 0.76,
            "totalLoadEnergy": 0.0,
            "pV2PowerStr": "193",
            "datetimeStr": "2024-08-24 18:05:00",
            "powernower": "N/A",
            "PVP": 499.0,
            "rGridCurrStr": "2.05",
            "totalLoadPowerWattStr": "1",
            "pV1StrCurr2Str": "N/A",
            "nowProwerStr": "498",
            "totalLoadEnergyStr": "2,633.88",
            "sOutVolt": 0.0,
            "ctGridPowerWattStr": "0",
            "rGridPowerVA": 769.0,
            "index": 1,
            "tGridVolt": 0.0,
            "todayFeedInEnergy": 10.33,
            "totalBatChgEnergyStr": "675.3",
            "tOnGridOutPowerWatt": 0.0,
            "pV3VoltStr": "0.1",
            "batPowerStr": "-1",
            "pV2Volt": 254.4,
            "deviceSn": "H1....592",
            "todayPVEnergyStr": "10.21",
            "pV3StrCurr3Str": "N/A",
            "rGridPowerWattStr": "494",
            "batCapicity": "200.00",
            "sGridCurrStr": "0.0",
            "sOutCurrStr": "0.0",
            "pV2StrCurr2": 0.0,
            "timeEnd": "null 23:59:59",
            "pV2StrCurr1": 0.0,
            "pV2StrCurr3Str": "N/A",
            "tOutPowerWattStr": "0",
            "tOutPowerVA": 0.0,
            "pV2StrCurr4": 0.0,
            "pV2StrCurr3": 0.0,
            "rOutFreq": 49.95,
            "plantuid": "",
            "endUser": "",
            "totalSellEnergy": 750.63,
            "sGridPowerWatt": 0.0,
            "pV1StrCurr3Str": "N/A",
            "rOnGridOutVolt": 240.3,
            "totalSellEnergyStr": "750.63",
            "deviceModel": "--",
            "batVolt": 51.9,
            "todaySellEnergy": 0.31,
            "totalFeedInEnergyStr": "667.01",
            "sOutVoltStr": "0",
            "timeStr": "",
            "pV3CurrStr": "0.0",
            "pV1Curr": 0.91,
            "sOutPowerWatt": 0.0,
            "pV3StrCurr1": 0.0,
            "pV3StrCurr2": 0.0,
            "rOnGridOutPowerWatt": 990.0,
            "pV3StrCurr3": 0.0,
            "pV3StrCurr4": 0.0,
            "pv4SeriesCurrent": "0.0-0.0-0.0-0.0",
            "kitSN": "--",
            "pV2StrCurr1Str": "N/A",
            "pV4Power": 0.0,
            "todaySellEnergyStr": "0.31",
            "sOutFreq": 0.0,
            "sGridCurr": 0.0,
            "typeStr": "\u50a8\u80fd\u9006\u53d8\u5668",
            "rGridVolt": 240.4,
            "rOutPowerVAStr": "9",
            "rOutCurrStr": "0.0",
            "pV4PowerStr": "0",
            "userUid": "",
            "pV2StrCurr2Str": "N/A",
            "pV4StrCurr1Str": "N/A",
            "ctGridPowerWatt": 0.0,
            "deviceTemp": 0.0,
            "pV2VoltStr": "254.4",
            "sOutFreqStr": "0",
            "batCurr": -0.84,
            "totalBatDisEnergyStr": "684.1",
            "pV1PowerStr": "306",
            "batEnergyPercentStr": "22",
            "pV1StrCurr4Str": "N/A",
            "ctPVPowerWatt": 0.0,
            "totalLoadPowerWatt": 1.0,
            "todaySelfConsumpEnergy": 0.0,
            "rOutVoltStr": "240.2",
            "todayLoadEnergyStr": "23.41",
            "rGridPowerWatt": 494.0,
            "sOutCurr": 0.0,
            "pV3StrCurr4Str": "N/A",
            "sGridFreq": 0.0,
            "tGridPowerVA": 0.0,
            "meterAStatus": 0,
            "pV1Volt": 335.8,
            "sOnGridOutVolt": 0.0,
            "todaySelfConsumpEnergyStr": "0",
            "plantName": ""
          }
        }
      ]
    }
  ],
  "pageHtml": "<ul>\n<li class=\"disabled\"><a href=\"javascript:;\">\u00ab Previous</a></li>\n<li class=\"active\"><a href=\"javascript:;\">1</a></li>\n<li class=\"disabled\"><a href=\"javascript:;\">Next \u00bb</a></li>\n<li class=\"disabled controls pageC\">Page <input type=\"text\" value=\"1\" onkeypress=\"var e=window.event||event;var c=e.keyCode||e.which;if(c==13)page(this.value,10,'');\" onclick=\"this.select();\"/> Total 1 Records</ul>\n<div style=\"clear:both;\"></div>",
  "status": "success"
}
```

Any idea what I'm potentially wrong in the configuration?

**Comment by acasandreiflorin** [comment]
Hi, I have a similar issue, after the latest update the chargeElec and dischargeElec are not reported anymore, the log shows the below:
saj_esolar: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/saj_esolar/sensor.py", line 1019, in async_update
    if 'dischargeElec' in energy['viewBean']:
                          ~~~~~~^^^^^^^^^^^^
KeyError: 'viewBean'


saj_esolar: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/saj_esolar/sensor.py", line 1015, in async_update
    if 'chargeElec' in energy['viewBean']:
                       ~~~~~~^^^^^^^^^^^^
KeyError: 'viewBean'

**Comment by cbaeyens** [comment]
I have the same issue

**Comment by djansen1987** [comment]
@jaesbit it seems like your pull request broke the some bits for these user, are you able to fix it or should we revert the you update?

**Comment by marcosturiale** [comment]
I have the same issue. 
Here there are the complete list of the resources that currently no longer return data after this update.

      - chargeElec 
      - dischargeElec
      - pvElec
      - useElec
      - buyElec
      - sellElec
      - buyRate
      - sellRate
      - selfConsumedRate1
      - selfConsumedRate2
      - selfConsumedEnergy1
      - selfConsumedEnergy2 


My Inverter is H1.

Thank you for your support.

**Comment by djansen1987** [comment]
Issue continuous in first report

https://github.com/djansen1987/SAJeSolar/issues/86
